In [1]:
import numpy as np

In [7]:
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
matriz = np.random.rand(3, 3)
print(matriz)

[[0.93168439 0.00097979 0.34399015]
 [0.94530352 0.75418768 0.46540917]
 [0.778632   0.63235946 0.83076824]]


In [12]:
midentidad = np.eye(4)
print(midentidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
vector_reshapeado = vector.reshape((2,5))
print(vector_reshapeado)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
#Seleccionar los elementos mayores a 5 del vector original y mostrarlos (1 punto)
vector_filtrado = vector[vector > 5]
print(vector_filtrado)


[ 6  7  8  9 10]


In [22]:
array1 = np.arange(1, 6)
array2 = np.arange(11, 16)
resultado = array1 + array2
print(resultado)

[1 2 3 4 5]
[11 12 13 14 15]
[12 14 16 18 20]


In [23]:
vector_raizcuadrada = np.sqrt(vector)
print(vector_raizcuadrada)

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]
